import './globals.css'
import "tw-elements/dist/css/tw-elements.min.css";

export const metadata = {
  title: 'E-commerce Web',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-screen h-screen bg-white">{children}</body>
    </html>
  )
}
